import type { Metadata } from "next"
import '@/stylesheet/reset.global.scss'
import "@/stylesheet/app.global.scss"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	generator: "Next.js",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning={true}>
			<body>{children}</body>
		</html>
	)
}
