import "@/stylesheet/reset.global.scss"
import type { Metadata } from "next"

export const metadata: Metadata = {
	title: "FontFight",
	description: "Generated by create next app",
	generator: "Next.js",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning={true}>
			<body>{children}</body>
		</html>
	)
}
